import {validateConfig} from "./config.mjs";
import {sanitizeMutation,readStatusRequest} from "./protocol.mjs";
import {createGenerationBinding} from "./binding.mjs";
import {connectUdsController} from "./uds-transport.mjs";
const deny=(message)=>({block:true,blockReason:message});
export function createPlugin({connectController=connectUdsController}={}){return{id:"controller-bound-authoritative-state",name:"Controller-bound Authoritative State",version:"0.1.0-prepackage.2",register(api){const config=validateConfig(api.pluginConfig);let binding;let retired=false;const requireBinding=()=>{if(retired||!binding)throw new Error("authoritative Controller is unavailable");binding.assertCurrent();return binding;};const respond=async(options,action)=>{try{options.respond(true,await action());}catch(error){options.respond(false,undefined,{code:"CONTROLLER_DENIED",message:error.message});}};
api.registerService({id:"controller-bound-authoritative-state-binding",reload:{configPrefixes:["plugins.entries.controller-bound-authoritative-state"]},async start(ctx){retired=false;const runtimeIdentity=ctx.internalDiagnostics?.getRuntimeIdentity?.();if(!runtimeIdentity)throw new Error("host-attested runtime identity is required");if(typeof connectController!=="function")throw new Error("Controller transport provider is unavailable");const transport=await connectController({socketPath:config.socketPath,protocolVersion:config.protocolVersion,connectTimeoutMs:config.connectTimeoutMs});binding=createGenerationBinding({transport,runtimeIdentity});await binding.request({type:"bind-generation",protocolVersion:config.protocolVersion});ctx.serviceHealth?.clearFailure();},async stop(){retired=true;binding?.revoke();binding=undefined;}});
api.registerGatewayMethod("controllerAuthoritativeState.status",options=>respond(options,async()=>requireBinding().request(readStatusRequest())),{scope:"operator.read",profileAccess:"required"});
api.registerGatewayMethod("controllerAuthoritativeState.mutate",options=>respond(options,async()=>{if(options.hasCurrentClientAuthority?.()!==true)throw new Error("current client authority is required");if(options.client?.authenticatedUserProfile?.profileId!==config.ownerProfileId)throw new Error("owner profile is required");return requireBinding().request({type:"mutation",body:sanitizeMutation(options.params)});}),{scope:"operator.admin",profileAccess:"required"});
api.on("before_agent_run",async()=>{try{await requireBinding().request({type:"admit",surface:"agent-run"});return{allow:true};}catch{return deny("authoritative Controller unavailable or denied agent run");}},{priority:1000});
api.on("before_tool_call",async event=>{try{await requireBinding().request({type:"admit",surface:"tool-call",toolName:event.toolName});}catch{return deny("authoritative Controller unavailable or denied tool call");}},{priority:1000});
}};}
export default createPlugin();
